### ISSUE TITLE
Weather (top-right)

### ISSUE THREAD

**Issue by marigerr** [chingu-voyage-turtles-team-5/momentum-clone#11]
Weather widget to be located at top-right of screen.    
Needs following features:

- [ ] show current weather temp for user's location
- [ ] show temperature with Fahrenheit scale if user is in US and Celsius for all other users
- [ ] show weather icon representing current weather conditions
- [ ] show user's town name
- [ ] design

**Comment by marigerr** [comment]
Possible issue to look into:
I am proponent of trying to get consent from user before looking up their IP information for location purposes.   I noticed that when installing Momentum extension, it has warning that it will know the user's location.   This is possibly a setting that is indicated when publishing the extension.

**Comment by jrpcoder** [comment]
Yes, I agree. But, I think it would be best to do it when the ext is installed, so it isn't asking for permission every time a new tab is open. What do you think?

**Comment by marigerr** [comment]
Yes sounds good!  I started playing around with it and tried out HTML5 geolocation but it doesn't seem to store the consent and instead requires it every time.   (there might be some way to configure to store it).   But I'll probably use something like ipinfo.io.

**Comment by jrpcoder** [comment]
Could we use something like the chrome storage api to store the consent locally?
Then it would just be a matter of fetching the consent automatically when a tab is open. If the consent doesn't exist initially, then the extension would ask the user for permission to use geolocation. Just an idea.
https://developer.chrome.com/apps/app_storage

**Comment by marigerr** [comment]
App storage looks really handy!   
I just found this also about how to add html5 geolocation permission to the manifest, so that it shouldn't have the consent pop-up and instead I think warns the user on extension install.   https://developer.chrome.com/extensions/declare_permissions#geolocation

**Comment by jrpcoder** [comment]
That could do it too. You can always access this API after permission, right? If so, it would be important for the "escape" feature.
