### ISSUE TITLE
CSS Layout / Positioning of "widgets"

### ISSUE THREAD

**Issue by marigerr** [chingu-voyage-turtles-team-5/momentum-clone#19]
I was wondering what everyone planned to do for positioning .   I have started on the weather widget in the  "top-right" and am using Flexbox.   But wondering what you are all planning to do?    Bootstrap?   Or perhaps just absolute positioning the top and bottom row of elements?   

It's my understanding that Chrome extensions only work on PCs so it's not necessary for the layout to look good on extra small screens.

I started making a skeleton layout with placeholders for all the widget areas using Flexbox.   I am going to push the branch `placeholders-layout` to github if anyone is interested in checking it out. 

Here is screen shot from new tab with placeholders:

![image](https://user-images.githubusercontent.com/15229372/28839203-29a0d54e-76f3-11e7-812e-f691b7128e0e.png)

**Comment by marigerr** [comment]
Ok great! I pushed a branch called [placeholders-layout](https://github.com/chingu-voyage-turtles-team-5/momentum-clone/tree/placeholders-layout) that has some some placeholders aligned with flexbox.

The branch might be something to try as a starter layout and tweak as we go along.   But can try other positioning techniques and/or just have each of us align our own elements as we code them. 

By the way, I think this [css tricks flexbox guide](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) is kind of handy reference.   What resource do you have?  I've also done a little on FCC and the [froggy tutorial](http://flexboxfroggy.com/)  :)

**Comment by jrpcoder** [comment]
Great! Yes, I've heard about the froggy tutorial too. But, I think I'll give a try to another one that uses "zombies" as a different  teaching approach :) Let's see.
http://geddski.teachable.com/p/flexbox-zombies
