### ISSUE TITLE
Task - Create User Stories and Assign

### ISSUE THREAD

**Issue by marigerr** [chingu-voyage-turtles-team-5/momentum-clone#4]
Tasks and Assignments From meeting:

1. Todo List (bottom-right);  Jose
2. Weather (top-right);  Maria
3. Links (top-left);  Grace
4. Search (top-left); Maria
5. Bookmark bar (top);  Maria
6. Time/greeting (upper-middle);  Grace
7. Focus todo (center-middle);  Jose
8. Random daily quote (bottom-middle); Jose
9. Wallpaper/author/description   Grace
10. settings menu (Bottom-left)  To be determined!

**Comment by marigerr** [comment]
Ideas for user stories:

- I receive new wallpaper everyday
- I can see the updated time (and date?) 
- When first loading the extension, I am asked for my name.
- My name is saved, and displayed in greeting thereafter. 
- I can see a input field with label "What is your main focus for today"
- I can enter my main focus for each day and it will be saved and displayed as a checklist 
- I can see the local weather in top right corner
- I can see a new quote each day
- The is a settings button in bottom left corner
- More!

**Comment by marigerr** [comment]
I had a couple questions about the top-left widget.   On the version of momentum that I have (v0.96.3).    The top-left widget has three icons.   
- Links
- Chrome Tab (switches back to normal Chrome New Tab)
- Apps

I don't see one for Search - which is one of my tasks (4 on list above.)  

Also, not to gum up our plans but wonder if it might be better to have one person work on the top-left widget as a whole, which includes task 3 & 4 from list above and possibly also adding functionality for the Apps Icon

If Grace is open to it, maybe her and I could trade tasks.   So I would do  3,4, 5.  And Grace would do 2, 6, 9

**Comment by marigerr** [comment]
I think we have completed this.  Goal was to get core issues added and assigned.  nice job! :)

**Comment by jrpcoder** [comment]
Yeap! I think so too. Should we archive it?

**Comment by marigerr** [comment]
sure!  that's a handy feature to clean up the column.
