### ISSUE TITLE
Gone

### ISSUE THREAD

**Issue by ativslife** [chingu-voyage-turtles-team-5/momentum-clone#50]
Wrong question

**Comment by marigerr** [comment]
Hi thanks for your interest!   This is a learning project that cloned a chrome extension [Momentum Dash ](https://chrome.google.com/webstore/detail/momentum/laookkfknpbbblfpciffpaejjkokdgca?hl=en).

Momentum Dash is not open source.   Our project's css and design layout currently is closely modeled after Momentum.    So not sure if it's possible to properly add a open source license this project as it is now.     

cc: @jrpcoder
