### ISSUE TITLE
Random daily quote (bottom-middle)

### ISSUE THREAD

**Issue by jrpcoder** [chingu-voyage-turtles-team-5/momentum-clone#7]
This feature will generate a random inspirational quote per day and display it (including the author) in the bottom-middle position of the screen. Additionally, there will be an option to tweet out the quote that shows on hover and a like/save button for the quote.

Tasks:
- [ ] Find/set up quote API;
- [ ] Generate feature HTML;
- [ ] Add functionality with jQuery;
- [ ] Design (CSS).

(issue configuration in progress)

**Comment by marigerr** [comment]
If there is time, there are 2 other features that show when hovering on the quote 
-  tweet out the quote that shows on hover 
-  like/save? the quote.

**Comment by jrpcoder** [comment]
Yeap, thanks!
